### ISSUE TITLE
incorporating components into keras-contrib

### ISSUE THREAD

**Issue by ahundt** [theduynguyen/Keras-FCN#4]
Hey, I liked the clean way you implemented some of this code and since it is MIT licensed I was planning on merging a couple things in [keras-contrib](https://github.com/farizrahman4u/keras-contrib) with attribution, but wanted to let you know!

Do you have any numbers for the kind of training results you got or idiosyncrasies I should know about?

**Comment by theduynguyen** [comment]
Hi Andrew,

this is very good news and definitely a big compliment for me. Feel free to use the code. Unfortunately, I stopped working on this project due to lack of time. Therefore, I did not generate any numbers. Feel free to ask if you have questions. I will try to answer them.

Best regards,
Duy

**Comment by ahundt** [comment]
cool, well if you wouldn't mind reviewing my version based on yours I'd appreciate it!
https://github.com/farizrahman4u/keras-contrib/pull/197

I had to make some changes to deal with numerical issues in a way that theano would support, and I went with a simpler way of flattening the data properly while maintaining channels in the results.

I think this issue itself can be closed, thanks!
